"""saves

Revision ID: 4a6dbbdf9e6b
Revises: f619739e486b
Create Date: 2026-09-24 03:39:08.475182
"""
from alembic import op
import sqlalchemy as sa


revision = '4a6dbbdf9e6b'
down_revision = 'f619739e486b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=64), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('blob', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_saves_player_game')
    )
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saves_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saves_player_id'))

    op.drop_table('saves')
    # ### end Alembic commands ###
