"""password resets

`players.pw_changed_at` is nullable on purpose rather than defaulted to now(): a sign-in token
carries the second it was minted, and deps.py refuses any token older than this column. Backfill
it with the time of the migration and every player signed in at deploy is signed out by it.
Null means "never reset", which is true of every row that exists when this runs.

Revision ID: bc2612acc605
Revises: 4a6dbbdf9e6b
Create Date: 2026-09-24 12:47:20.618307
"""
from alembic import op
import sqlalchemy as sa


revision = 'bc2612acc605'
down_revision = '4a6dbbdf9e6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pw_changed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('pw_changed_at')

    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_resets_player_id'))

    op.drop_table('password_resets')
    # ### end Alembic commands ###
