"""players, free runs per game, licences

Revision ID: f619739e486b
Revises: 
Create Date: 2026-09-24 02:46:02.058950
"""
from alembic import op
import sqlalchemy as sa


revision = 'f619739e486b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_email'), ['email'], unique=True)

    op.create_table('free_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=64), nullable=False),
    sa.Column('weeks', sa.Integer(), nullable=False),
    sa.Column('first_week_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_week_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_free_runs_player_game')
    )
    with op.batch_alter_table('free_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_free_runs_player_id'), ['player_id'], unique=False)

    op.create_table('licences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('instance_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('store_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_licences_key')
    )
    with op.batch_alter_table('licences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licences_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licences_player_id'))

    op.drop_table('licences')
    with op.batch_alter_table('free_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_free_runs_player_id'))

    op.drop_table('free_runs')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_email'))

    op.drop_table('players')
    # ### end Alembic commands ###
