/* EVERY CITY'S SKYLINE, ON ONE PAGE.
 *
 *     node tools/skyline-sheet.js      # writes city-skylines.html
 *
 * There is nothing to collect. The 586 drawings in art/ are files; a skyline is not — it is
 * generated by citySkyline(city,country) from a seed made of the city's name and its country's
 * terrain, which is the only reason 129 of them are affordable at all. So this asks the GAME for
 * them, one call per city, rather than drawing its own: run it after the generator changes and the
 * sheet changes with it.
 *
 * It reads tests/thecrew_check.js — the script carved out of play.html — under the same DOM stub
 * the node suites use, and lifts the .sky-* rules out of play.html so the page shows the card's own
 * lines rather than a lookalike. The output is one self-contained file: no network, no fonts, no
 * images, and sections that do not break across a printed page. */
const fs=require("fs");
const path=require("path");
const ROOT=path.resolve(__dirname,"..");
const src=fs.readFileSync(path.join(ROOT,"tests","thecrew_check.js"),"utf8");
const mk=id=>({id,style:{setProperty(){},removeProperty(){}},classList:{add(){},remove(){},contains:()=>false,toggle(){}},children:[],dataset:{},innerHTML:"",value:"",textContent:"",hidden:false,scrollTop:0,scrollHeight:0,setAttribute(){},getAttribute:()=>null,appendChild(){},insertAdjacentHTML(){},querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){},removeEventListener(){},getBoundingClientRect:()=>({left:0,top:0,width:100,height:100,right:100,bottom:100}),focus(){},select(){},play:()=>Promise.resolve(),pause(){},load(){},scrollIntoView(){},closest:()=>null,remove(){},contains:()=>false,setSelectionRange(){},paused:true,volume:1,loop:false,src:""});
const ELS={};global.store={};
global.localStorage={getItem:()=>null,setItem(){},removeItem(){}};
global.document={getElementById:id=>ELS[id]||(ELS[id]=mk(id)),querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){},createElement:mk,body:mk("body"),documentElement:mk("html"),hidden:false};
global.window={matchMedia:()=>({matches:false}),addEventListener(){},scrollTo(){},innerWidth:1200,innerHeight:800,localStorage:global.localStorage,document:global.document,location:{href:"",search:""},navigator:{language:"en"}};
global.navigator={language:"en"};global.requestAnimationFrame=()=>0;global.Audio=function(){return mk("audio");};
global.fetch=()=>Promise.reject(new Error("x"));global.URL={createObjectURL:()=>"x"};global.scrollTo=()=>{};global.setInterval=()=>1;global.clearInterval=()=>{};
global.SAVE=d=>{
  const css=fs.readFileSync(path.join(ROOT,"play.html"),"utf8")
    .split("\n").filter(l=>/^\s*\.sky(-|\{)/.test(l)).join("\n");
  const esc=t=>String(t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
  const by=new Map();
  d.forEach(x=>{const k=x.country;if(!by.has(k))by.set(k,{flag:x.flag,terrain:x.terrain,items:[]});by.get(k).items.push(x);});
  let sections="";
  for(const [country,g] of by){
    const tiles=g.items.map(x=>'<figure class="t"><div class="f">'+x.svg+'</div><figcaption><b>'+esc(x.city)+'</b></figcaption></figure>').join("");
    sections+='<section><h2><span class="fl">'+g.flag+'</span>'+esc(country)+'<span class="ter">'+esc(g.terrain)+'</span></h2><div class="grid">'+tiles+'</div></section>';
  }
  const doc='<!doctype html>\n<meta charset="utf-8">\n<title>The Crew \u2014 every city\u2019s skyline</title>\n'
   +'<meta name="viewport" content="width=device-width,initial-scale=1">\n<style>\n'
   +':root{--paper:#f6f4ee;--card:#fbfaf6;--ink:#111010}\n*{box-sizing:border-box}\n'
   +'body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 "Helvetica Neue",Helvetica,Arial,sans-serif;padding:28px 20px 70px}\n'
   +'header{max-width:1180px;margin:0 auto 28px}h1{font:600 30px/1.2 "Helvetica Neue",Helvetica,Arial,sans-serif;margin:0 0 8px;letter-spacing:-.01em}\n'
   +'.sub{opacity:.7;margin:0;max-width:64ch}main{max-width:1180px;margin:0 auto}\n'
   +'section{margin:0 0 30px;border-top:1px solid rgba(17,16,16,.16);padding-top:14px}\n'
   +'h2{font:600 15px/1.3 "Helvetica Neue",Helvetica,Arial,sans-serif;margin:0 0 12px;letter-spacing:.09em;text-transform:uppercase;display:flex;align-items:baseline;gap:9px}\n'
   +'.fl{font-size:19px}.ter{margin-left:auto;font-weight:400;text-transform:none;letter-spacing:0;opacity:.5;font-size:13px}\n'
   +'.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:16px}.t{margin:0}\n'
   +'.f{background:var(--card);border:1px solid rgba(17,16,16,.16);padding:10px 10px 4px}figcaption{margin-top:6px;font-size:13px}\n'
   +'/* lifted from play.html, so these are the card\u2019s own lines */\n'+css+'\n'
   +'@media print{body{padding:0}section{break-inside:avoid}}\n</style>\n'
   +'<header><h1>Every city\u2019s skyline</h1><p class="sub">All '+d.length+' cities across '+by.size
   +' countries, as the establishing card draws them. Nothing here is a stored picture: each one is generated '
   +'from the city\u2019s name and its country\u2019s terrain, so it is the same every time that city comes up and '
   +'different from every other city. Landmarks appear where a city has one, and the skyline drops to make room '
   +'for it.</p></header>\n<main>'+sections+'</main>\n';
  fs.writeFileSync(path.join(ROOT,"city-skylines.html"),doc);
  console.log("wrote city-skylines.html \u2014 "+d.length+" cities, "+by.size+" countries, "+Math.round(doc.length/1024)+" KB");
};

require("vm").runInThisContext(src+`
;(function(){
  const out=[];
  COUNTRIES.forEach(co=>{
    (co.cities||[]).forEach(city=>{
      let svg="";
      try{ svg=citySkyline(city,co.name); }catch(e){ svg="<!-- "+e.message+" -->"; }
      out.push({city,country:co.name,flag:co.flag,terrain:(co.terrain||[]).join(", "),svg});
    });
  });
  SAVE(out);
  console.log("rendered "+out.length+" skylines across "+COUNTRIES.length+" countries");
})();
`,{filename:"sky.js"});
